# Generated by Django 5.1.2 on 2024-10-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
