# Generated by Django 5.1.2 on 2024-10-23 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_token', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
