# Generated by Django 5.1.2 on 2024-10-23 03:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_token', '0002_emailtoken_used_alter_emailtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
